"""
Strategy Dashboard 템플릿

Strategic Blueprint을 전문적인 Dashboard 형식으로 출력
"""
from typing import Dict, Any


STRATEGY_DASHBOARD_TEMPLATE = """
# 📊 Strategic Investment Blueprint
Generated: {date} | Confidence: {confidence}%

---

## 🎯 Investment Strategy Summary

**Market Cycle**: {market_cycle}
**Strategic Stance**: {strategic_stance}
**Recommended Allocation**: Stocks {stock_ratio}% | Cash {cash_ratio}%

{summary}

---

## 📈 Market Cycle Analysis

**Current Phase**: {market_cycle_detail}

{market_analysis}

**Key Market Indicators**:
{market_indicators}

---

## 🏭 Sector Allocation Strategy

**Overweight Sectors** (높은 비중 권장):
{overweight_sectors}

**Underweight Sectors** (낮은 비중 권장):
{underweight_sectors}

**Rationale**: {sector_rationale}

---

## 💰 Asset Allocation Breakdown

```
Stocks:  {stock_ratio}% [{stock_bar}]
Cash:    {cash_ratio}% [{cash_bar}]
```

**Allocation Rationale**: {allocation_rationale}

**Portfolio Constraints**:
- 최대 종목 수: {max_stocks}개
- 종목당 최대 비중: {max_per_stock}%
- 최소 종목 수: {min_stocks}개

---

## 🎬 Investment Action Plan

{action_plan}

---

## ⚠️ Risk Management Framework

**Stop-Loss Triggers**:
{stop_loss_triggers}

**Rebalancing Conditions**:
{rebalancing_conditions}

**Key Assumptions to Monitor**:
{key_assumptions}

---

## 💡 Next Steps

{next_steps}

---

*This blueprint is generated by AI and should be used as a decision support tool. Always conduct your own due diligence.*
"""


def build_strategy_dashboard_prompt(
    market_outlook: Dict[str, Any],
    sector_strategy: Dict[str, Any],
    asset_allocation: Dict[str, Any],
    investment_style: Dict[str, Any],
    risk_tolerance: str,
    constraints: Dict[str, Any],
    confidence_score: float,
    key_assumptions: list,
) -> str:
    """
    Strategy Dashboard 생성 프롬프트

    Args:
        market_outlook: 시장 전망
        sector_strategy: 섹터 전략
        asset_allocation: 자산 배분
        investment_style: 투자 스타일
        risk_tolerance: 리스크 허용도
        constraints: 제약 조건
        confidence_score: 신뢰도
        key_assumptions: 주요 가정

    Returns:
        Dashboard 생성 프롬프트
    """
    from ..utils import build_prompt
    from datetime import datetime

    # 컨텍스트 데이터 준비
    context = {
        "market_cycle": market_outlook.get("cycle", "expansion"),
        "market_confidence": market_outlook.get("confidence", 0.75),
        "market_summary": market_outlook.get("summary", ""),
        "overweight_sectors": sector_strategy.get("overweight", []),
        "underweight_sectors": sector_strategy.get("underweight", []),
        "sector_rationale": sector_strategy.get("rationale", ""),
        "stock_ratio": asset_allocation.get("stocks", 0.7),
        "cash_ratio": asset_allocation.get("cash", 0.3),
        "allocation_rationale": asset_allocation.get("rationale", ""),
        "investment_style": investment_style.get("type", "growth"),
        "horizon": investment_style.get("horizon", "mid_term"),
        "risk_tolerance": risk_tolerance,
        "max_stocks": constraints.get("max_stocks", 10),
        "max_per_stock": constraints.get("max_per_stock", 0.20),
        "min_stocks": constraints.get("min_stocks", 5),
        "confidence_score": confidence_score,
        "key_assumptions": key_assumptions,
    }

    task = """위의 전략 분석 결과를 바탕으로 전문적인 Strategic Investment Blueprint Dashboard를 생성하세요.

요구사항:
1. **명확성**: 투자자가 즉시 이해할 수 있도록 간결하고 명확하게 작성
2. **실행 가능성**: 구체적인 액션 아이템 포함 (다음 주에 무엇을 할 것인가?)
3. **리스크 관리**: 손절 기준, 리밸런싱 조건 명시
4. **데이터 기반**: 정량적 수치와 근거 포함

Dashboard 섹션별 가이드:

**Investment Strategy Summary**:
- Strategic Stance는 시장 사이클과 리스크 허용도를 종합하여 결정 (예: "Moderate Bullish", "Defensive")
- 핵심 전략을 2-3문장으로 요약

**Market Cycle Analysis**:
- 현재 사이클 단계의 특징 설명
- 주요 지표 3-5개 나열 (예: "KOSPI +15% YTD", "IT 섹터 outperformance")

**Sector Allocation Strategy**:
- Overweight/Underweight 섹터 각각 3-5개 나열
- 각 섹터에 대한 간단한 근거 포함

**Investment Action Plan**:
- 구체적인 실행 단계 (예: "1주차: IT 섹터 25% 배분", "2주차: 리밸런싱")
- 우선순위 표시

**Risk Management Framework**:
- Stop-Loss Triggers: 어떤 상황에서 전략을 포기할 것인가?
- Rebalancing Conditions: 언제 포트폴리오를 조정할 것인가?

**Next Steps**:
- 이번 주/다음 주에 해야 할 구체적인 액션 3-5개"""

    output_format = f"""다음 템플릿을 채워서 반환하세요:

{STRATEGY_DASHBOARD_TEMPLATE}

템플릿 변수 설명:
- {{date}}: 현재 날짜 (YYYY-MM-DD 형식)
- {{confidence}}: 신뢰도 (0-100)
- {{market_cycle}}: "확장기", "정점", "수축기", "저점" 중 하나
- {{strategic_stance}}: "Aggressive Bullish", "Moderate Bullish", "Neutral", "Defensive" 등
- {{stock_ratio}}, {{cash_ratio}}: 자산 배분 비율 (정수)
- {{summary}}: 2-3문장 요약
- {{market_cycle_detail}}: 시장 사이클 상세 설명 (2-3문장)
- {{market_analysis}}: 시장 분석 (3-4문장)
- {{market_indicators}}: 주요 지표 리스트 (불릿 포인트)
- {{overweight_sectors}}, {{underweight_sectors}}: 섹터 리스트 (불릿 포인트, 각 섹터에 근거 포함)
- {{sector_rationale}}: 섹터 전략 근거 (2-3문장)
- {{allocation_rationale}}: 자산 배분 근거 (2-3문장)
- {{stock_bar}}, {{cash_bar}}: 막대 그래프 (예: "▓▓▓▓▓▓▓░░░")
- {{max_stocks}}, {{max_per_stock}}, {{min_stocks}}: 포트폴리오 제약
- {{action_plan}}: 실행 계획 (번호 매긴 리스트)
- {{stop_loss_triggers}}: 손절 트리거 (불릿 포인트)
- {{rebalancing_conditions}}: 리밸런싱 조건 (불릿 포인트)
- {{key_assumptions}}: 주요 가정 (불릿 포인트)
- {{next_steps}}: 다음 단계 (번호 매긴 리스트)

**중요**: 템플릿을 그대로 사용하되, {{}} 안의 모든 변수를 실제 값으로 채워야 합니다."""

    examples = [
        {
            "input": "확장기, 주식 70%, IT/금융 overweight",
            "output": """# 📊 Strategic Investment Blueprint
Generated: 2025-01-15 | Confidence: 85%

---

## 🎯 Investment Strategy Summary

**Market Cycle**: 확장기 (Expansion)
**Strategic Stance**: Moderate Bullish
**Recommended Allocation**: Stocks 70% | Cash 30%

경기 확장기 진입과 함께 IT·금융 섹터를 중심으로 공격적 성장 전략을 구사합니다. 다만 변동성 대비 현금 30% 보유로 리스크를 관리합니다.

---

## 📈 Market Cycle Analysis

**Current Phase**: 확장기 초입 - 경기 회복세 지속

KOSPI가 저점 대비 12% 반등하며 확장기 진입 신호를 보이고 있습니다. IT 업종을 중심으로 실적 개선이 뚜렷하며, 금리 인하 기대감이 시장을 지지하고 있습니다.

**Key Market Indicators**:
- KOSPI +12% from recent low
- IT sector leading with +18% performance
- Foreign investors net buying for 5 consecutive weeks
- VIX declining to 14 (low volatility environment)

---

## 🏭 Sector Allocation Strategy

**Overweight Sectors** (높은 비중 권장):
- **IT (정보기술)**: AI·반도체 업황 회복, 글로벌 수요 증가
- **금융**: 금리 안정화, NIM 개선 기대
- **소비재**: 소비심리 회복, 명절 특수 기대

**Underweight Sectors** (낮은 비중 권장):
- **에너지**: 유가 불확실성, 수급 불균형
- **소재**: 중국 경기 둔화 영향

**Rationale**: 확장기 초입에는 경기 민감 업종(IT, 금융)이 강세를 보이며, 방어적 섹터는 상대적으로 부진한 패턴이 역사적으로 반복되어 왔습니다.

---

## 💰 Asset Allocation Breakdown

```
Stocks:  70% [▓▓▓▓▓▓▓░░░]
Cash:    30% [▓▓▓░░░░░░░]
```

**Allocation Rationale**: 확장기 특성상 주식 비중을 70%로 높이되, 변동성 대비 현금 30% 보유로 급락 시 추가 매수 여력을 확보합니다.

**Portfolio Constraints**:
- 최대 종목 수: 10개
- 종목당 최대 비중: 20%
- 최소 종목 수: 5개

---

## 🎬 Investment Action Plan

1. **1주차**: IT 섹터 25% 배분 (삼성전자, SK하이닉스 등 대형주 중심)
2. **2주차**: 금융 섹터 20% 배분 (KB금융, 신한지주)
3. **3주차**: 소비재 15% 배분 (LG생활건강, 아모레퍼시픽)
4. **4주차**: 나머지 10% 배분 및 포트폴리오 리뷰

---

## ⚠️ Risk Management Framework

**Stop-Loss Triggers**:
- KOSPI가 주봉 기준 200일 이평선 하향 이탈
- IT 섹터가 2주 연속 -5% 이상 하락
- 금리 급등 (10년물 국고채 +50bp 이상)

**Rebalancing Conditions**:
- 월 1회 정기 리밸런싱
- 섹터 비중이 목표 대비 ±5%p 이상 이탈 시
- 시장 사이클 전환 신호 포착 시

**Key Assumptions to Monitor**:
- 확장기 국면 지속 (KOSPI 상승 추세 유지)
- IT 섹터 실적 개선 지속
- 금리 안정화 (급격한 변동 없음)

---

## 💡 Next Steps

1. **이번 주**: 증권사 계좌 점검 및 현금 확보
2. **다음 주**: IT 대형주 25% 매수 (분할 매수)
3. **2주 후**: 금융주 추가 매수 및 포트폴리오 밸런스 확인
4. **월말**: 첫 리밸런싱 및 수익률 점검

---

*This blueprint is generated by AI and should be used as a decision support tool. Always conduct your own due diligence.*"""
        }
    ]

    guidelines = """1. 모든 템플릿 변수를 실제 값으로 채울 것
2. 막대 그래프는 10칸 기준 (예: 70% = 7칸 ▓, 3칸 ░)
3. 날짜는 현재 날짜 사용
4. 신뢰도는 0-100 정수로 표시
5. 섹터명은 한글 사용, 괄호 안에 영문 표기 가능
6. 수치는 소수점 이하 반올림 (예: 70%, not 70.0%)
7. 불릿 포인트는 "-" 사용
8. 번호 리스트는 "1.", "2." 형식 사용"""

    return build_prompt(
        role="Strategic Blueprint Dashboard Generator",
        context=context,
        task=task,
        output_format=output_format,
        examples=examples,
        guidelines=guidelines,
    )
